package com.anondo.quizapppractice

object Bangladesh {
    val question = mutableListOf<Quiz>(

        // Geography (1-20)
        Quiz("What is the capital of Bangladesh?", listOf("Chittagong", "Dhaka", "Sylhet", "Rajshahi"), 1),
        Quiz("Which is the largest city in Bangladesh?", listOf("Chittagong", "Dhaka", "Sylhet", "Khulna"), 1),
        Quiz("How many divisions are in Bangladesh?", listOf("6", "7", "8", "9"), 2),
        Quiz("Which is the longest river in Bangladesh?", listOf("Padma", "Meghna", "Jamuna", "Brahmaputra"), 0),
        Quiz("What is the largest river port in Bangladesh?", listOf("Mongla", "Narayanganj", "Chandpur", "Barisal"), 1),
        Quiz("What is the largest sea port in Bangladesh?", listOf("Chittagong", "Mongla", "Payra", "Cox's Bazar"), 0),
        Quiz("Which is the longest sea beach in the world?", listOf("Miami Beach", "Cox's Bazar", "Patenga", "Kuakata"), 1),
        Quiz("What is the area of Bangladesh?", listOf("147,570 sq km", "148,460 sq km", "150,000 sq km", "145,000 sq km"), 0),
        Quiz("Which country surrounds Bangladesh from three sides?", listOf("Pakistan", "India", "Myanmar", "Nepal"), 1),
        Quiz("Which sea is located south of Bangladesh?", listOf("Arabian Sea", "Bay of Bengal", "Indian Ocean", "Red Sea"), 1),
        Quiz("What is the highest peak in Bangladesh?", listOf("Keokradong", "Tajiendong", "Mowdok Mual", "Raikhiang"), 1),
        Quiz("Which district is known as the land of rivers?", listOf("Barisal", "Sylhet", "Khulna", "Chittagong"), 0),
        Quiz("Where is the Sundarbans located?", listOf("Chittagong", "Khulna", "Sylhet", "Rajshahi"), 1),
        Quiz("What is the national animal of Bangladesh?", listOf("Tiger", "Elephant", "Royal Bengal Tiger", "Deer"), 2),
        Quiz("What is the national bird of Bangladesh?", listOf("Parrot", "Doel", "Crow", "Sparrow"), 1),
        Quiz("What is the national flower of Bangladesh?", listOf("Rose", "Shapla", "Lotus", "Sunflower"), 1),
        Quiz("What is the national fruit of Bangladesh?", listOf("Mango", "Jackfruit", "Banana", "Lychee"), 1),
        Quiz("Which river is known as the sorrow of Bangladesh?", listOf("Padma", "Meghna", "Brahmaputra", "Surma"), 2),
        Quiz("How many districts are in Bangladesh?", listOf("60", "64", "68", "70"), 1),
        Quiz("Which is the smallest district in Bangladesh?", listOf("Narayanganj", "Meherpur", "Narsingdi", "Lakshmipur"), 1),

        // Liberation War (21-40)
        Quiz("When did Bangladesh gain independence?", listOf("1970", "1971", "1972", "1973"), 1),
        Quiz("On which date is Independence Day celebrated?", listOf("16 December", "26 March", "21 February", "14 December"), 1),
        Quiz("On which date is Victory Day celebrated?", listOf("16 December", "26 March", "21 February", "14 December"), 0),
        Quiz("Who declared independence of Bangladesh?", listOf("Tajuddin Ahmad", "Bangabandhu Sheikh Mujibur Rahman", "Ziaur Rahman", "Khandaker Mushtaq"), 1),
        Quiz("How many sectors were in Liberation War?", listOf("9", "10", "11", "12"), 2),
        Quiz("Who was the first Prime Minister of Bangladesh?", listOf("Bangabandhu Sheikh Mujibur Rahman", "Tajuddin Ahmad", "Nazrul Islam", "Syed Nazrul Islam"), 1),
        Quiz("Where was the Mujibnagar government formed?", listOf("Dhaka", "Meherpur", "Jessore", "Kushtia"), 1),
        Quiz("When was Mujibnagar government formed?", listOf("26 March 1971", "17 April 1971", "16 December 1971", "21 February 1971"), 1),
        Quiz("Who was the commander-in-chief of Liberation War?", listOf("Ziaur Rahman", "M. A. G. Osmani", "Khaled Mosharraf", "K M Shafiullah"), 1),
        Quiz("How long did the Liberation War last?", listOf("8 months", "9 months", "10 months", "11 months"), 1),
        Quiz("What is the national memorial of Bangladesh?", listOf("Shaheed Minar", "Jatiyo Smriti Soudho", "Central Shaheed Minar", "Ahsan Manzil"), 1),
        Quiz("Where is Jatiyo Smriti Soudho located?", listOf("Dhaka", "Savar", "Chittagong", "Sylhet"), 1),
        Quiz("Who wrote the national anthem of Bangladesh?", listOf("Kazi Nazrul Islam", "Rabindranath Tagore", "Jasimuddin", "Shamsur Rahman"), 1),
        Quiz("Who composed the music of national anthem?", listOf("Rabindranath Tagore", "Kazi Nazrul Islam", "Satyajit Ray", "Salil Chowdhury"), 0),
        Quiz("When is Shaheed Dibosh celebrated?", listOf("16 December", "26 March", "21 February", "14 December"), 2),
        Quiz("Why is 21 February significant?", listOf("Independence Day", "Language Movement", "Victory Day", "National Day"), 1),
        Quiz("Who is the Father of the Nation?", listOf("Ziaur Rahman", "Bangabandhu Sheikh Mujibur Rahman", "Tajuddin Ahmad", "Sher-e-Bangla"), 1),
        Quiz("When was Bangabandhu assassinated?", listOf("1972", "1975", "1981", "1971"), 1),
        Quiz("How many freedom fighters got Bir Sreshtho title?", listOf("5", "6", "7", "8"), 2),
        Quiz("What was Operation Searchlight?", listOf("Liberation plan", "Pakistani military operation", "Indian help", "Naval operation"), 1),

        // Politics & Government (41-55)
        Quiz("What is the parliament of Bangladesh called?", listOf("Lok Sabha", "Jatiya Sangsad", "National Assembly", "Congress"), 1),
        Quiz("How many seats are in Bangladesh Parliament?", listOf("300", "350", "345", "330"), 1),
        Quiz("Who is the head of state in Bangladesh?", listOf("Prime Minister", "President", "Speaker", "Chief Justice"), 1),
        Quiz("Who is the head of government in Bangladesh?", listOf("President", "Prime Minister", "Speaker", "Chief Justice"), 1),
        Quiz("What is the currency of Bangladesh?", listOf("Rupee", "Taka", "Dollar", "Pound"), 1),
        Quiz("What is the largest political party in Bangladesh?", listOf("BNP", "Awami League", "Jatiya Party", "Jamaat"), 1),
        Quiz("Who founded Awami League?", listOf("Bangabandhu", "Maulana Bhashani", "Both A&B", "Tajuddin Ahmad"), 2),
        Quiz("When was Awami League founded?", listOf("1947", "1949", "1952", "1971"), 1),
        Quiz("What is the highest court in Bangladesh?", listOf("High Court", "Supreme Court", "District Court", "Appellate Court"), 1),
        Quiz("How many years is a parliamentary term?", listOf("3", "4", "5", "6"), 2),
        Quiz("What is the voting age in Bangladesh?", listOf("16", "18", "21", "25"), 1),
        Quiz("Who was the first president of Bangladesh?", listOf("Bangabandhu Sheikh Mujibur Rahman", "Abu Sayem", "Ziaur Rahman", "Hussain Muhammad Ershad"), 0),
        Quiz("What is the national emblem of Bangladesh?", listOf("Shapla", "Tiger", "Water lily with rice", "Flag"), 2),
        Quiz("How many colors are in Bangladesh flag?", listOf("1", "2", "3", "4"), 1),
        Quiz("What does the red circle in flag represent?", listOf("Blood", "Sun", "Both A&B", "Victory"), 2),

        // Culture & Heritage (56-70)
        Quiz("What is the traditional dress for women in Bangladesh?", listOf("Shalwar Kameez", "Saree", "Lehenga", "Kurti"), 1),
        Quiz("What is the traditional dress for men in Bangladesh?", listOf("Kurta", "Panjabi", "Lungi", "Both B&C"), 3),
        Quiz("What is the main religion in Bangladesh?", listOf("Hinduism", "Islam", "Buddhism", "Christianity"), 1),
        Quiz("Which festival is the largest in Bangladesh?", listOf("Eid", "Durga Puja", "Pohela Boishakh", "Christmas"), 0),
        Quiz("When is Bengali New Year celebrated?", listOf("1 January", "14 April", "26 March", "21 February"), 1),
        Quiz("What is the Bengali New Year called?", listOf("Noboborsho", "Pohela Boishakh", "Both A&B", "Baishakhi"), 2),
        Quiz("Which poet is known as Bidrohi Kobi?", listOf("Rabindranath Tagore", "Kazi Nazrul Islam", "Jasimuddin", "Jibanananda Das"), 1),
        Quiz("Who won the Nobel Prize from Bangladesh region?", listOf("Kazi Nazrul Islam", "Rabindranath Tagore", "Muhammad Yunus", "Both B&C"), 3),
        Quiz("Who is known as Rebel Poet?", listOf("Rabindranath Tagore", "Kazi Nazrul Islam", "Sukanta Bhattacharya", "Shamsur Rahman"), 1),
        Quiz("What is the famous folk music of Bangladesh?", listOf("Baul", "Classical", "Pop", "Rock"), 0),
        Quiz("Who is the most famous Baul singer?", listOf("Lalon Shah", "Hason Raja", "Both A&B", "Abdul Alim"), 2),
        Quiz("What is Pahela Baishakh?", listOf("Independence Day", "Bengali New Year", "Victory Day", "Language Day"), 1),
        Quiz("Which UNESCO World Heritage Site is in Bangladesh?", listOf("Ahsan Manzil", "Sundarbans", "Lalbagh Fort", "National Museum"), 1),
        Quiz("Where is the historic Lalbagh Fort?", listOf("Old Dhaka", "Chittagong", "Sylhet", "Rajshahi"), 0),
        Quiz("What is the famous river cruise destination?", listOf("Padma", "Sundarbans", "Sangu", "Karnaphuli"), 1),

        // Economy & Development (71-85)
        Quiz("What is the main industry of Bangladesh?", listOf("Agriculture", "Garments", "IT", "Tourism"), 1),
        Quiz("What is the main export of Bangladesh?", listOf("Rice", "Garments", "Fish", "Tea"), 1),
        Quiz("Which crop is most cultivated in Bangladesh?", listOf("Wheat", "Rice", "Jute", "Cotton"), 1),
        Quiz("What is Bangladesh known as in jute production?", listOf("Golden Fiber", "Jute capital", "Both A&B", "Green gold"), 2),
        Quiz("What is the industrial capital of Bangladesh?", listOf("Dhaka", "Chittagong", "Narayanganj", "Gazipur"), 2),
        Quiz("Which bank is the central bank of Bangladesh?", listOf("Sonali Bank", "Bangladesh Bank", "Janata Bank", "Agrani Bank"), 1),
        Quiz("Who founded Grameen Bank?", listOf("Fazle Hasan Abed", "Muhammad Yunus", "Rehman Sobhan", "A. K. Azad"), 1),
        Quiz("When did Muhammad Yunus win Nobel Prize?", listOf("2004", "2005", "2006", "2007"), 2),
        Quiz("What is the literacy rate of Bangladesh approximately?", listOf("65%", "70%", "75%", "80%"), 2),
        Quiz("Which sector employs most people in Bangladesh?", listOf("Industry", "Agriculture", "Service", "IT"), 1),
        Quiz("What is the main power source in Bangladesh?", listOf("Solar", "Natural Gas", "Hydro", "Coal"), 1),
        Quiz("Which bridge connects South Bengal with Dhaka?", listOf("Jamuna Bridge", "Padma Bridge", "Meghna Bridge", "Karnaphuli Bridge"), 1),
        Quiz("Where is the longest bridge in Bangladesh?", listOf("Padma Bridge", "Jamuna Bridge", "Meghna Bridge", "Buriganga Bridge"), 0),
        Quiz("What is the main source of foreign currency?", listOf("Tourism", "Remittance", "Export", "Both B&C"), 3),
        Quiz("Which organization was founded by Fazle Hasan Abed?", listOf("Grameen Bank", "BRAC", "Asha", "Proshika"), 1),

        // Education & Sports (86-100)
        Quiz("What is the oldest university in Bangladesh?", listOf("Dhaka University", "Rajshahi University", "Chittagong University", "Jahangirnagar University"), 0),
        Quiz("When was Dhaka University established?", listOf("1911", "1921", "1931", "1947"), 1),
        Quiz("Which is the first private university in Bangladesh?", listOf("NSU", "BRAC University", "North South University", "IUB"), 2),
        Quiz("What is the national sport of Bangladesh?", listOf("Football", "Kabaddi", "Cricket", "Hockey"), 1),
        Quiz("Which sport is most popular in Bangladesh?", listOf("Football", "Kabaddi", "Cricket", "Hockey"), 2),
        Quiz("When did Bangladesh get Test status in cricket?", listOf("1998", "2000", "2002", "2004"), 1),
        Quiz("Who is the most successful Bangladesh cricketer?", listOf("Shakib Al Hasan", "Mashrafe Mortaza", "Tamim Iqbal", "Mushfiqur Rahim"), 0),
        Quiz("Which Bangladesh cricketer is ICC ranked no. 1?", listOf("Tamim Iqbal", "Shakib Al Hasan", "Mustafizur Rahman", "Mushfiqur Rahim"), 1),
        Quiz("Where is the main cricket stadium in Dhaka?", listOf("Sher-e-Bangla Stadium", "MA Aziz Stadium", "Bangabandhu Stadium", "Shaheed Chandu Stadium"), 0),
        Quiz("Which year did Bangladesh reach World Cup quarter-final?", listOf("2011", "2015", "2019", "2023"), 1),
        Quiz("What is the highest educational degree in Bangladesh?", listOf("Masters", "PhD", "MPhil", "Post-doc"), 1),
        Quiz("Which board conducts SSC and HSC exams?", listOf("BISE", "Education Board", "Both A&B", "University Grants Commission"), 2),
        Quiz("How many education boards are in Bangladesh?", listOf("8", "9", "10", "11"), 3),
        Quiz("What is the first satellite of Bangladesh?", listOf("Bangabandhu-1", "Bangladesh-1", "Bangla Sat-1", "BD Sat-1"), 0),
        Quiz("When was Bangabandhu Satellite-1 launched?", listOf("2016", "2017", "2018", "2019"), 2),

        // Additional Facts (101-110)
        Quiz("What is the population of Bangladesh approximately?", listOf("140 million", "160 million", "170 million", "180 million"), 2),
        Quiz("What is the official language of Bangladesh?", listOf("Urdu", "Bengali", "English", "Hindi"), 1),
        Quiz("Which script is used for Bengali language?", listOf("Devanagari", "Bengali Script", "Arabic", "Latin"), 1),
        Quiz("What is the calling code of Bangladesh?", listOf("+88", "+880", "+91", "+92"), 1),
        Quiz("What is the internet domain of Bangladesh?", listOf(".bd", ".bg", ".ban", ".bdsh"), 0),
        Quiz("Which airline is the national carrier?", listOf("Regent Airways", "Biman Bangladesh", "Novo Air", "US-Bangla"), 1),
        Quiz("What is the time zone of Bangladesh?", listOf("GMT+5", "GMT+6", "GMT+5:30", "GMT+7"), 1),
        Quiz("Which famous personality is from Tungipara?", listOf("Kazi Nazrul Islam", "Bangabandhu Sheikh Mujibur Rahman", "Rabindranath Tagore", "Ziaur Rahman"), 1),
        Quiz("What is the national mosque of Bangladesh?", listOf("Baitul Mukarram", "Star Mosque", "Sixty Dome Mosque", "Khan Mohammad Mridha Mosque"), 0),
        Quiz("Which city is called the city of mosques?", listOf("Chittagong", "Dhaka", "Sylhet", "Bagerhat"), 1)
    )
}