package com.anondo.quizapppractice

object Islam {
    val question = mutableListOf<Quiz>(

        // Basic Islamic Knowledge (1-20)
        Quiz("How many pillars of Islam are there?", listOf("3", "4", "5", "6"), 2),
        Quiz("What is the first pillar of Islam?", listOf("Salah", "Shahada", "Zakat", "Hajj"), 1),
        Quiz("How many times do Muslims pray daily?", listOf("3", "4", "5", "6"), 2),
        Quiz("What is the holy book of Islam?", listOf("Bible", "Quran", "Torah", "Vedas"), 1),
        Quiz("Who is the last prophet of Islam?", listOf("Prophet Ibrahim", "Prophet Musa", "Prophet Muhammad (PBUH)", "Prophet Isa"), 2),
        Quiz("What is the first month of Islamic calendar?", listOf("Ramadan", "Muharram", "Shawwal", "Dhul Hijjah"), 1),
        Quiz("In which month do Muslims fast?", listOf("Muharram", "Ramadan", "Shawwal", "Rajab"), 1),
        Quiz("What is the direction Muslims face during prayer?", listOf("North", "Qibla", "East", "West"), 1),
        Quiz("Where is the Kaaba located?", listOf("Medina", "Makkah", "Jerusalem", "Cairo"), 1),
        Quiz("What is Zakat?", listOf("Prayer", "Fasting", "Charity", "Pilgrimage"), 2),
        Quiz("What is the meaning of Islam?", listOf("Peace", "Submission", "Both A&B", "Prayer"), 2),
        Quiz("What is the Arabic word for God?", listOf("Rab", "Allah", "Ilah", "Rabb"), 1),
        Quiz("How many surahs are in the Quran?", listOf("100", "114", "120", "99"), 1),
        Quiz("What is the longest surah in the Quran?", listOf("Al-Fatiha", "Al-Baqarah", "Al-Imran", "An-Nisa"), 1),
        Quiz("What is the shortest surah in the Quran?", listOf("Al-Asr", "Al-Kawthar", "Al-Ikhlas", "An-Nas"), 1),
        Quiz("How many verses are in Surah Al-Fatiha?", listOf("5", "7", "9", "10"), 1),
        Quiz("What is the night of power called?", listOf("Laylat al-Miraj", "Laylat al-Qadr", "Shab-e-Barat", "Shab-e-Meraj"), 1),
        Quiz("Which angel brought revelations to prophets?", listOf("Mikail", "Jibreel", "Israfil", "Azrael"), 1),
        Quiz("What is the day of judgment called?", listOf("Qiyamah", "Akhirah", "Jannah", "Jahannam"), 0),
        Quiz("How many prophets are mentioned in the Quran?", listOf("15", "20", "25", "30"), 2),

        // Prophets (21-35)
        Quiz("Who was the first prophet?", listOf("Prophet Nuh", "Prophet Adam", "Prophet Ibrahim", "Prophet Musa"), 1),
        Quiz("Which prophet built the Ark?", listOf("Prophet Ibrahim", "Prophet Nuh", "Prophet Musa", "Prophet Yunus"), 1),
        Quiz("Which prophet was thrown into fire?", listOf("Prophet Yusuf", "Prophet Ibrahim", "Prophet Musa", "Prophet Isa"), 1),
        Quiz("Which prophet could talk to animals?", listOf("Prophet Musa", "Prophet Sulaiman", "Prophet Dawud", "Prophet Isa"), 1),
        Quiz("Which prophet was swallowed by a whale?", listOf("Prophet Musa", "Prophet Yunus", "Prophet Yusuf", "Prophet Nuh"), 1),
        Quiz("Which prophet received the Torah?", listOf("Prophet Isa", "Prophet Musa", "Prophet Dawud", "Prophet Ibrahim"), 1),
        Quiz("Which prophet received the Injil (Gospel)?", listOf("Prophet Musa", "Prophet Isa", "Prophet Dawud", "Prophet Muhammad"), 1),
        Quiz("Which prophet received the Zabur (Psalms)?", listOf("Prophet Musa", "Prophet Dawud", "Prophet Isa", "Prophet Sulaiman"), 1),
        Quiz("Who was Prophet Muhammad's (PBUH) father?", listOf("Abu Talib", "Abdullah", "Abu Bakr", "Abbas"), 1),
        Quiz("Who was Prophet Muhammad's (PBUH) mother?", listOf("Khadijah", "Aminah", "Fatimah", "Aisha"), 1),
        Quiz("In which year was Prophet Muhammad (PBUH) born?", listOf("570 CE", "571 CE", "580 CE", "590 CE"), 0),
        Quiz("In which city was Prophet Muhammad (PBUH) born?", listOf("Medina", "Makkah", "Taif", "Jerusalem"), 1),
        Quiz("At what age did Prophet Muhammad (PBUH) receive first revelation?", listOf("30", "35", "40", "45"), 2),
        Quiz("Which prophet was father of Prophet Yusuf?", listOf("Prophet Ibrahim", "Prophet Yaqub", "Prophet Ishaq", "Prophet Ismail"), 1),
        Quiz("Which prophet split the sea?", listOf("Prophet Nuh", "Prophet Musa", "Prophet Isa", "Prophet Ibrahim"), 1),

        // Quran & Revelation (36-50)
        Quiz("In which cave did Prophet receive first revelation?", listOf("Cave Thawr", "Cave Hira", "Cave Uhud", "Cave Badr"), 1),
        Quiz("What was the first word revealed in the Quran?", listOf("Allah", "Muhammad", "Iqra", "Bismillah"), 2),
        Quiz("Which surah is called the heart of Quran?", listOf("Al-Fatiha", "Ya-Sin", "Al-Baqarah", "Al-Ikhlas"), 1),
        Quiz("Which surah does not begin with Bismillah?", listOf("Al-Fatiha", "At-Tawbah", "Al-Ikhlas", "An-Nas"), 1),
        Quiz("How many Juz are in the Quran?", listOf("20", "25", "30", "35"), 2),
        Quiz("Which surah is equal to 1/3 of Quran?", listOf("Al-Fatiha", "Al-Ikhlas", "Al-Kawthar", "An-Nas"), 1),
        Quiz("What are the last two surahs of Quran called?", listOf("Mu'awwidhatayn", "Mufassal", "Makki", "Madani"), 0),
        Quiz("How many years did it take to reveal the Quran?", listOf("20", "23", "25", "30"), 1),
        Quiz("Which surah mentions two prophets in its name?", listOf("Surah Ibrahim", "Surah Yusuf", "Surah Muhammad", "Surah Luqman"), 1),
        Quiz("What is the opening surah of Quran?", listOf("Al-Baqarah", "Al-Fatiha", "An-Nas", "Al-Ikhlas"), 1),
        Quiz("Which surah is called 'The Cow'?", listOf("Al-Fatiha", "Al-Baqarah", "Al-Imran", "An-Nisa"), 1),
        Quiz("Which surah mentions a spider?", listOf("Al-Ankabut", "An-Naml", "An-Nahl", "Ad-Dahr"), 0),
        Quiz("Which surah mentions an ant?", listOf("Al-Ankabut", "An-Naml", "An-Nahl", "Ad-Dahr"), 1),
        Quiz("Which surah mentions a bee?", listOf("Al-Ankabut", "An-Naml", "An-Nahl", "Ad-Dahr"), 2),
        Quiz("In which language was Quran revealed?", listOf("Persian", "Arabic", "Hebrew", "Urdu"), 1),

        // Salah & Worship (51-65)
        Quiz("How many rakats are in Fajr prayer?", listOf("2", "3", "4", "5"), 0),
        Quiz("How many rakats are in Dhuhr prayer?", listOf("2", "3", "4", "5"), 2),
        Quiz("How many rakats are in Asr prayer?", listOf("2", "3", "4", "5"), 2),
        Quiz("How many rakats are in Maghrib prayer?", listOf("2", "3", "4", "5"), 1),
        Quiz("How many rakats are in Isha prayer?", listOf("2", "3", "4", "5"), 2),
        Quiz("What is the call to prayer called?", listOf("Iqamah", "Adhan", "Takbir", "Tasbih"), 1),
        Quiz("What is said before starting prayer?", listOf("Salam", "Takbir", "Taslim", "Tahmid"), 1),
        Quiz("What is the pillar of prayer that means bowing?", listOf("Sujud", "Ruku", "Qiyam", "Tashahhud"), 1),
        Quiz("What is the pillar of prayer that means prostration?", listOf("Sujud", "Ruku", "Qiyam", "Tashahhud"), 0),
        Quiz("Which prayer is offered on Eid?", listOf("Janazah", "Taraweeh", "Eid Salah", "Tahajjud"), 2),
        Quiz("Which prayer is offered at night in Ramadan?", listOf("Janazah", "Taraweeh", "Duha", "Tahajjud"), 1),
        Quiz("What is the night prayer called?", listOf("Fajr", "Tahajjud", "Duha", "Witr"), 1),
        Quiz("Which direction should a Muslim face to pray?", listOf("East", "Kaaba", "North", "Jerusalem"), 1),
        Quiz("How many times is Takbir said in Eid prayer?", listOf("5", "7", "12", "15"), 2),
        Quiz("What must be performed before prayer?", listOf("Ghusl", "Wudu", "Tayammum", "Fasting"), 1),

        // Hajj & Ramadan (66-80)
        Quiz("In which Islamic month is Hajj performed?", listOf("Ramadan", "Shawwal", "Dhul Hijjah", "Muharram"), 2),
        Quiz("How many days is Hajj?", listOf("3", "5", "7", "10"), 1),
        Quiz("What is the day of Arafah?", listOf("8th Dhul Hijjah", "9th Dhul Hijjah", "10th Dhul Hijjah", "11th Dhul Hijjah"), 1),
        Quiz("What is the day of Eid al-Adha?", listOf("8th Dhul Hijjah", "9th Dhul Hijjah", "10th Dhul Hijjah", "11th Dhul Hijjah"), 2),
        Quiz("How many times must Kaaba be circled in Tawaf?", listOf("5", "7", "10", "12"), 1),
        Quiz("What is walking between Safa and Marwa called?", listOf("Tawaf", "Sa'i", "Wuquf", "Rami"), 1),
        Quiz("What is the standing at Arafat called?", listOf("Tawaf", "Sa'i", "Wuquf", "Rami"), 2),
        Quiz("What is stoning the devil called?", listOf("Tawaf", "Sa'i", "Wuquf", "Rami"), 3),
        Quiz("Which night in Ramadan is better than 1000 months?", listOf("15th night", "27th night", "29th night", "1st night"), 1),
        Quiz("What is the pre-dawn meal in Ramadan called?", listOf("Iftar", "Suhoor", "Taraweeh", "Zakat"), 1),
        Quiz("What is the meal to break fast called?", listOf("Iftar", "Suhoor", "Taraweeh", "Zakat"), 0),
        Quiz("How many days are in Ramadan?", listOf("28", "29 or 30", "30", "31"), 1),
        Quiz("What is Eid after Ramadan called?", listOf("Eid al-Fitr", "Eid al-Adha", "Eid Mubarak", "Eid Milad"), 0),
        Quiz("What is Eid after Hajj called?", listOf("Eid al-Fitr", "Eid al-Adha", "Eid Mubarak", "Eid Milad"), 1),
        Quiz("What charity is given at end of Ramadan?", listOf("Zakat", "Sadaqah", "Zakat al-Fitr", "Khums"), 2),

        // Islamic History (81-95)
        Quiz("Who was the first caliph?", listOf("Umar", "Abu Bakr", "Uthman", "Ali"), 1),
        Quiz("Who was the second caliph?", listOf("Abu Bakr", "Umar", "Uthman", "Ali"), 1),
        Quiz("Who compiled the Quran in book form?", listOf("Abu Bakr", "Umar", "Uthman", "Ali"), 2),
        Quiz("What is the migration to Medina called?", listOf("Hijrah", "Hajj", "Umrah", "Jihad"), 0),
        Quiz("In which year did Hijrah occur?", listOf("610 CE", "622 CE", "630 CE", "632 CE"), 1),
        Quiz("What was Medina called before Islam?", listOf("Makkah", "Yathrib", "Taif", "Badr"), 1),
        Quiz("Which battle was the first in Islamic history?", listOf("Battle of Uhud", "Battle of Badr", "Battle of Khandaq", "Battle of Hunayn"), 1),
        Quiz("In which year did the conquest of Makkah occur?", listOf("622 CE", "624 CE", "630 CE", "632 CE"), 2),
        Quiz("Who was known as Al-Farooq?", listOf("Abu Bakr", "Umar", "Uthman", "Ali"), 1),
        Quiz("Who was known as Dhun-Nurayn?", listOf("Abu Bakr", "Umar", "Uthman", "Ali"), 2),
        Quiz("Who was Prophet Muhammad's (PBUH) first wife?", listOf("Aisha", "Khadijah", "Hafsa", "Fatimah"), 1),
        Quiz("Who was Prophet Muhammad's (PBUH) daughter?", listOf("Aisha", "Khadijah", "Fatimah", "Hafsa"), 2),
        Quiz("Which companion was called 'The Truthful'?", listOf("Abu Bakr", "Umar", "Uthman", "Ali"), 0),
        Quiz("In which year did Prophet Muhammad (PBUH) pass away?", listOf("630 CE", "632 CE", "634 CE", "636 CE"), 1),
        Quiz("How old was Prophet when he passed away?", listOf("60", "63", "65", "70"), 1),

        // Angels & Beliefs (96-110)
        Quiz("How many angels are mentioned carrying the Throne?", listOf("4", "6", "8", "10"), 2),
        Quiz("Which angel is responsible for rain?", listOf("Jibreel", "Mikail", "Israfil", "Azrael"), 1),
        Quiz("Which angel will blow the trumpet?", listOf("Jibreel", "Mikail", "Israfil", "Azrael"), 2),
        Quiz("Which angel takes souls?", listOf("Jibreel", "Mikail", "Israfil", "Azrael"), 3),
        Quiz("How many heavens are there in Islam?", listOf("5", "6", "7", "8"), 2),
        Quiz("What are the beings created from fire called?", listOf("Angels", "Jinn", "Humans", "Demons"), 1),
        Quiz("What were humans created from?", listOf("Fire", "Light", "Clay", "Water"), 2),
        Quiz("What were angels created from?", listOf("Fire", "Light", "Clay", "Water"), 1),
        Quiz("What is paradise called in Islam?", listOf("Jannah", "Jahannam", "Akhirah", "Barzakh"), 0),
        Quiz("What is hell called in Islam?", listOf("Jannah", "Jahannam", "Akhirah", "Barzakh"), 1),
        Quiz("How many gates does Jannah have?", listOf("5", "7", "8", "10"), 2),
        Quiz("How many gates does Jahannam have?", listOf("5", "7", "8", "10"), 1),
        Quiz("What is the bridge over hell called?", listOf("Mizan", "Sirat", "Araf", "Barzakh"), 1),
        Quiz("What are the scales on Day of Judgment called?", listOf("Mizan", "Sirat", "Araf", "Lauh"), 0),
        Quiz("How many articles of faith are there?", listOf("4", "5", "6", "7"), 2)
    )
}